import { defineNode } from './define.js';
import type { NodeDefinition } from './types.js';

const LLM_FIELDS = [
  {
    kind: 'select' as const,
    key: 'provider',
    label: 'Provider',
    required: true,
    options: [
      { label: 'Claude', value: 'anthropic' },
      { label: 'OpenAI', value: 'openai' },
    ],
  },
  {
    kind: 'text' as const,
    key: 'model',
    label: 'Model',
    placeholder: 'Leave blank for the server default',
    help: 'Examples: claude-sonnet-4-5, gpt-4.1-mini',
  },
];

const IN = [{ id: 'in', label: 'In' }];
const OUT = [{ id: 'out', label: 'Out' }];

export const nodeCatalog: NodeDefinition[] = [
  defineNode({
    type: 'trigger.manual',
    category: 'trigger',
    label: 'Manual',
    description: 'Starts when you tap Run.',
    icon: 'play',
    color: '#5B8DEF',
    fields: [
      {
        kind: 'json',
        key: 'sampleInput',
        label: 'Sample input',
        help: 'JSON object passed in as the trigger payload during a test run.',
        placeholder: '{ "text": "hello" }',
      },
    ],
    inputs: [],
    outputs: OUT,
    defaults: {},
  }),
  defineNode({
    type: 'trigger.schedule',
    category: 'trigger',
    label: 'Schedule',
    description: 'Starts on a cron schedule.',
    icon: 'time',
    color: '#5B8DEF',
    fields: [
      {
        kind: 'cron',
        key: 'cron',
        label: 'Cron',
        required: true,
        placeholder: '0 8 * * *',
        help: 'Five fields: minute hour day month weekday. Example: 0 8 * * 1-5 is 8:00 on weekdays.',
      },
    ],
    inputs: [],
    outputs: OUT,
    defaults: { cron: '0 8 * * *' },
  }),
  defineNode({
    type: 'trigger.webhook',
    category: 'trigger',
    label: 'Webhook',
    description: 'Starts when something POSTs to a secret URL.',
    icon: 'link',
    color: '#5B8DEF',
    fields: [
      {
        kind: 'text',
        key: 'description',
        label: 'Note',
        placeholder: 'Form submissions',
      },
    ],
    inputs: [],
    outputs: OUT,
  }),
  defineNode({
    type: 'trigger.gmail_new_email',
    category: 'trigger',
    label: 'New email',
    description: 'Starts when a matching Gmail message arrives.',
    icon: 'mail',
    color: '#5B8DEF',
    provider: 'gmail',
    fields: [
      {
        kind: 'text',
        key: 'query',
        label: 'Gmail search',
        placeholder: 'is:unread -category:promotions',
        help: 'Same syntax as the Gmail search box. Leave blank to watch the inbox.',
      },
    ],
    inputs: [],
    outputs: OUT,
    defaults: { query: 'is:inbox' },
  }),
  defineNode({
    type: 'trigger.slack_message',
    category: 'trigger',
    label: 'Slack message',
    description: 'Starts when a Slack message arrives.',
    icon: 'chatbubbles',
    color: '#5B8DEF',
    provider: 'slack',
    fields: [
      {
        kind: 'text',
        key: 'channel',
        label: 'Channel ID',
        placeholder: 'C0123456789',
        help: 'Leave blank to accept any channel the Slack app can see.',
      },
    ],
    inputs: [],
    outputs: OUT,
  }),
  defineNode({
    type: 'trigger.notion_item_added',
    category: 'trigger',
    label: 'Notion item added',
    description: 'Starts when a database row is created or edited.',
    icon: 'document-text',
    color: '#5B8DEF',
    provider: 'notion',
    fields: [
      {
        kind: 'text',
        key: 'databaseId',
        label: 'Database ID',
        required: true,
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      },
    ],
    inputs: [],
    outputs: OUT,
  }),
  defineNode({
    type: 'ai.prompt',
    category: 'ai',
    label: 'LLM prompt',
    description: 'One model call. Use {{ }} to insert earlier outputs.',
    icon: 'sparkles',
    color: '#C084FC',
    fields: [
      ...LLM_FIELDS,
      { kind: 'textarea', key: 'system', label: 'System prompt', placeholder: 'You are a careful assistant.' },
      { kind: 'textarea', key: 'prompt', label: 'Prompt', required: true, placeholder: 'Summarize {{nodes.trigger.subject}}' },
      {
        kind: 'select',
        key: 'outputMode',
        label: 'Output',
        options: [
          { label: 'Text', value: 'text' },
          { label: 'JSON', value: 'json' },
        ],
      },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { provider: 'anthropic', outputMode: 'text' },
  }),
  defineNode({
    type: 'ai.agent',
    category: 'ai',
    label: 'AI agent',
    description: 'A tool-calling loop. Connect action nodes to the Tools port.',
    icon: 'hardware-chip',
    color: '#C084FC',
    fields: [
      ...LLM_FIELDS,
      { kind: 'textarea', key: 'system', label: 'System prompt' },
      { kind: 'textarea', key: 'prompt', label: 'Goal', required: true },
      {
        kind: 'number',
        key: 'maxIterations',
        label: 'Max tool rounds',
        min: 1,
        max: 8,
        help: 'How many times the model may call tools before it must answer.',
      },
    ],
    inputs: IN,
    outputs: [
      { id: 'out', label: 'Out' },
      { id: 'tools', label: 'Tools' },
    ],
    defaults: { provider: 'anthropic', maxIterations: 5 },
  }),
  defineNode({
    type: 'ai.classify',
    category: 'ai',
    label: 'Classify',
    description: 'Picks one category from a list you provide.',
    icon: 'funnel',
    color: '#C084FC',
    fields: [
      ...LLM_FIELDS,
      { kind: 'textarea', key: 'input', label: 'Text to classify', required: true },
      {
        kind: 'text',
        key: 'categories',
        label: 'Categories',
        required: true,
        placeholder: 'Urgent, Later, FYI',
        help: 'Comma-separated.',
      },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { provider: 'anthropic', categories: 'Urgent, Later, FYI' },
  }),
  defineNode({
    type: 'gmail.send',
    category: 'action',
    label: 'Send email',
    description: 'Sends an email from the connected Gmail account.',
    icon: 'send',
    color: '#3DDC97',
    provider: 'gmail',
    sideEffect: true,
    asTool: { description: 'Send an email from the user Gmail account.' },
    fields: [
      { kind: 'text', key: 'to', label: 'To', required: true, placeholder: 'person@example.com' },
      { kind: 'text', key: 'subject', label: 'Subject', required: true },
      { kind: 'textarea', key: 'body', label: 'Body', required: true },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'gmail.reply',
    category: 'action',
    label: 'Reply to email',
    description: 'Replies in an existing Gmail thread.',
    icon: 'return-down-back',
    color: '#3DDC97',
    provider: 'gmail',
    sideEffect: true,
    asTool: { description: 'Reply to an existing Gmail message.' },
    fields: [
      { kind: 'text', key: 'messageId', label: 'Message ID', required: true, placeholder: '{{nodes.trigger.id}}' },
      { kind: 'text', key: 'threadId', label: 'Thread ID', placeholder: '{{nodes.trigger.threadId}}' },
      { kind: 'text', key: 'to', label: 'To', placeholder: '{{nodes.trigger.from}}' },
      { kind: 'text', key: 'subject', label: 'Subject', placeholder: 'Re: {{nodes.trigger.subject}}' },
      { kind: 'textarea', key: 'body', label: 'Body', required: true },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'gmail.search',
    category: 'action',
    label: 'Search email',
    description: 'Reads matching Gmail messages.',
    icon: 'search',
    color: '#3DDC97',
    provider: 'gmail',
    asTool: { description: 'Search the user Gmail inbox.' },
    fields: [
      { kind: 'text', key: 'query', label: 'Query', required: true, placeholder: 'from:boss newer_than:1d' },
      { kind: 'number', key: 'maxResults', label: 'Max results', min: 1, max: 20 },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { maxResults: 5 },
  }),
  defineNode({
    type: 'gcal.create_event',
    category: 'action',
    label: 'Create event',
    description: 'Adds an event to Google Calendar.',
    icon: 'calendar',
    color: '#3DDC97',
    provider: 'gcal',
    sideEffect: true,
    asTool: { description: 'Create a Google Calendar event.' },
    fields: [
      { kind: 'text', key: 'summary', label: 'Title', required: true },
      { kind: 'text', key: 'start', label: 'Start (ISO)', required: true, placeholder: '2026-09-26T15:00:00-05:00' },
      { kind: 'text', key: 'end', label: 'End (ISO)', required: true },
      { kind: 'textarea', key: 'description', label: 'Description' },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'gcal.list_events',
    category: 'action',
    label: 'List events',
    description: 'Reads upcoming Google Calendar events.',
    icon: 'calendar-outline',
    color: '#3DDC97',
    provider: 'gcal',
    asTool: { description: 'List events on the user primary calendar.' },
    fields: [
      { kind: 'text', key: 'timeMin', label: 'From (ISO)', help: 'Leave blank to start from now.' },
      { kind: 'text', key: 'timeMax', label: 'To (ISO)' },
      { kind: 'number', key: 'maxResults', label: 'Max results', min: 1, max: 25 },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { maxResults: 10 },
  }),
  defineNode({
    type: 'slack.post_message',
    category: 'action',
    label: 'Post to Slack',
    description: 'Posts a message to a Slack channel.',
    icon: 'logo-slack',
    color: '#3DDC97',
    provider: 'slack',
    sideEffect: true,
    asTool: { description: 'Post a message to Slack.' },
    fields: [
      { kind: 'text', key: 'channel', label: 'Channel ID', required: true, placeholder: 'C0123456789' },
      { kind: 'textarea', key: 'text', label: 'Message', required: true },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'notion.create_page',
    category: 'action',
    label: 'Create Notion page',
    description: 'Creates a page in a database or under another page.',
    icon: 'add-circle',
    color: '#3DDC97',
    provider: 'notion',
    sideEffect: true,
    asTool: { description: 'Create a Notion page.' },
    fields: [
      { kind: 'text', key: 'databaseId', label: 'Database ID', help: 'Provide a database ID or a parent page ID.' },
      { kind: 'text', key: 'parentPageId', label: 'Parent page ID' },
      { kind: 'text', key: 'titleProperty', label: 'Title property', placeholder: 'Name' },
      { kind: 'text', key: 'title', label: 'Title', required: true },
      { kind: 'textarea', key: 'content', label: 'Content' },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { titleProperty: 'Name' },
  }),
  defineNode({
    type: 'notion.update_page',
    category: 'action',
    label: 'Update Notion page',
    description: 'Appends a paragraph to an existing page.',
    icon: 'create',
    color: '#3DDC97',
    provider: 'notion',
    sideEffect: true,
    asTool: { description: 'Append text to a Notion page.' },
    fields: [
      { kind: 'text', key: 'pageId', label: 'Page ID', required: true },
      { kind: 'textarea', key: 'content', label: 'Content', required: true },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'notion.query_database',
    category: 'action',
    label: 'Query Notion database',
    description: 'Reads rows from a Notion database.',
    icon: 'server',
    color: '#3DDC97',
    provider: 'notion',
    asTool: { description: 'Query a Notion database.' },
    fields: [
      { kind: 'text', key: 'databaseId', label: 'Database ID', required: true },
      {
        kind: 'json',
        key: 'filter',
        label: 'Filter JSON',
        help: 'Optional Notion filter object.',
        placeholder: '{ "property": "Status", "status": { "equals": "Done" } }',
      },
      { kind: 'number', key: 'pageSize', label: 'Page size', min: 1, max: 20 },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { pageSize: 10 },
  }),
  defineNode({
    type: 'excel.append_row',
    category: 'action',
    label: 'Append Excel row',
    description: 'Adds a row to a worksheet in OneDrive.',
    icon: 'grid',
    color: '#3DDC97',
    provider: 'excel',
    sideEffect: true,
    asTool: { description: 'Append a row to an Excel workbook on OneDrive.' },
    fields: [
      {
        kind: 'text',
        key: 'workbookPath',
        label: 'Workbook path',
        required: true,
        placeholder: 'Documents/Leads.xlsx',
        help: 'Path inside the connected OneDrive.',
      },
      { kind: 'text', key: 'worksheet', label: 'Worksheet', required: true, placeholder: 'Sheet1' },
      {
        kind: 'text',
        key: 'values',
        label: 'Values',
        required: true,
        placeholder: '{{nodes.trigger.name}}, {{nodes.trigger.email}}',
        help: 'Comma-separated cells, or a JSON array.',
      },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'excel.read_range',
    category: 'action',
    label: 'Read Excel range',
    description: 'Reads cells from a OneDrive workbook.',
    icon: 'reader',
    color: '#3DDC97',
    provider: 'excel',
    asTool: { description: 'Read a range from an Excel workbook.' },
    fields: [
      { kind: 'text', key: 'workbookPath', label: 'Workbook path', required: true },
      { kind: 'text', key: 'worksheet', label: 'Worksheet', required: true, placeholder: 'Sheet1' },
      { kind: 'text', key: 'range', label: 'Range', required: true, placeholder: 'A1:D20' },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'http.request',
    category: 'action',
    label: 'HTTP request',
    description: 'Calls any HTTP API. Writes are skipped in a test run.',
    icon: 'globe',
    color: '#3DDC97',
    sideEffect: true,
    asTool: { description: 'Make an HTTP request.' },
    fields: [
      {
        kind: 'select',
        key: 'method',
        label: 'Method',
        required: true,
        options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map((value) => ({ label: value, value })),
      },
      { kind: 'text', key: 'url', label: 'URL', required: true, placeholder: 'https://api.example.com/items' },
      {
        kind: 'textarea',
        key: 'headers',
        label: 'Headers',
        placeholder: 'Authorization: Bearer ...',
        help: 'One Key: Value pair per line, or a JSON object.',
      },
      { kind: 'textarea', key: 'body', label: 'Body' },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { method: 'GET' },
  }),
  defineNode({
    type: 'logic.if',
    category: 'logic',
    label: 'If / else',
    description: 'Sends the run down the true or false branch.',
    icon: 'git-branch',
    color: '#E08A4F',
    fields: [
      { kind: 'text', key: 'left', label: 'Value', required: true, placeholder: '{{nodes.classify.category}}' },
      {
        kind: 'select',
        key: 'operator',
        label: 'Operator',
        required: true,
        options: [
          { label: 'equals', value: 'eq' },
          { label: 'does not equal', value: 'neq' },
          { label: 'contains', value: 'contains' },
          { label: 'greater than', value: 'gt' },
          { label: 'less than', value: 'lt' },
          { label: 'exists', value: 'exists' },
          { label: 'is empty', value: 'not_exists' },
        ],
      },
      { kind: 'text', key: 'right', label: 'Compare to', placeholder: 'Urgent' },
    ],
    inputs: IN,
    outputs: [
      { id: 'true', label: 'True' },
      { id: 'false', label: 'False' },
    ],
    defaults: { operator: 'eq' },
  }),
  defineNode({
    type: 'logic.switch',
    category: 'logic',
    label: 'Switch',
    description: 'Matches a value against up to three cases.',
    icon: 'options',
    color: '#E08A4F',
    fields: [
      { kind: 'text', key: 'value', label: 'Value', required: true },
      { kind: 'text', key: 'case1', label: 'Case 1' },
      { kind: 'text', key: 'case2', label: 'Case 2' },
      { kind: 'text', key: 'case3', label: 'Case 3' },
    ],
    inputs: IN,
    outputs: [
      { id: 'case1', label: 'Case 1' },
      { id: 'case2', label: 'Case 2' },
      { id: 'case3', label: 'Case 3' },
      { id: 'default', label: 'Default' },
    ],
  }),
  defineNode({
    type: 'logic.delay',
    category: 'logic',
    label: 'Delay',
    description: 'Waits before continuing. Longer waits are queued.',
    icon: 'hourglass',
    color: '#E08A4F',
    fields: [
      { kind: 'number', key: 'seconds', label: 'Seconds', required: true, min: 1, max: 86400 },
    ],
    inputs: IN,
    outputs: OUT,
    defaults: { seconds: 30 },
  }),
  defineNode({
    type: 'logic.loop',
    category: 'logic',
    label: 'Loop',
    description: 'Runs the Each branch once per item, then continues on Done.',
    icon: 'repeat',
    color: '#E08A4F',
    fields: [
      {
        kind: 'text',
        key: 'items',
        label: 'List',
        required: true,
        placeholder: '{{nodes.search.messages}}',
        help: 'A template that resolves to an array. Inside the loop, use {{vars.item}} and {{vars.index}}.',
      },
      { kind: 'number', key: 'max', label: 'Max items', min: 1, max: 50 },
    ],
    inputs: IN,
    outputs: [
      { id: 'each', label: 'Each' },
      { id: 'done', label: 'Done' },
    ],
    defaults: { max: 25 },
  }),
  defineNode({
    type: 'logic.set_variable',
    category: 'logic',
    label: 'Set variable',
    description: 'Saves a value you can read later as {{vars.name}}.',
    icon: 'pricetag',
    color: '#E08A4F',
    fields: [
      { kind: 'text', key: 'name', label: 'Name', required: true, placeholder: 'summary' },
      { kind: 'textarea', key: 'value', label: 'Value', required: true },
    ],
    inputs: IN,
    outputs: OUT,
  }),
  defineNode({
    type: 'logic.approval',
    category: 'logic',
    label: 'Approval',
    description: 'Pauses until you approve or reject on your phone.',
    icon: 'checkmark-circle',
    color: '#E08A4F',
    fields: [
      {
        kind: 'textarea',
        key: 'summary',
        label: 'What should the user confirm?',
        required: true,
        placeholder: 'Send this reply?\n\n{{nodes.draft.text}}',
      },
    ],
    inputs: IN,
    outputs: [
      { id: 'approved', label: 'Approved' },
      { id: 'rejected', label: 'Rejected' },
    ],
  }),
];

const byType = new Map(nodeCatalog.map((node) => [node.type, node]));

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return byType.get(type);
}

export function listNodeDefinitions(): NodeDefinition[] {
  return nodeCatalog;
}
